Fix mypy errors caused by new version of mypy (#5485)
Fixes mypy errors caused by new versions of mypy, which showed up as:

```
arkouda/numpy/pdarraysetops.py:519: error: Item "Strings" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
arkouda/numpy/pdarraysetops.py:519: error: Item "Categorical" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
arkouda/numpy/pdarraysetops.py:520: error: Item "Strings" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
arkouda/numpy/pdarraysetops.py:520: error: Item "Categorical" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
arkouda/numpy/pdarraysetops.py:525: error: Item "Strings" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
arkouda/numpy/pdarraysetops.py:525: error: Item "Categorical" of "pdarray | Strings | Categorical" has no attribute "max_bits"  [union-attr]
```

Signed-off-by: Jade Abraham <jade.abraham@hpe.com>